import "server-only";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { ReportAgentOutput } from "@/lib/validation/agent";
import type { ReportMetrics } from "@/lib/ai/agents/report-agent";

/**
 * "Branded enterprise report layout" (Phase 6 scope) rendered server-side
 * via @react-pdf/renderer — pure JS, no headless-browser dependency, so it
 * runs in a standard Vercel serverless function without the Puppeteer/
 * Chromium deployment complexity that would otherwise be needed.
 * Design System §2/§3 tokens (indigo-violet primary, Inter-adjacent
 * typography scale) are approximated here since @react-pdf/renderer can't
 * consume the app's CSS variables directly — colors/spacing are hardcoded
 * to match Design System §2.1's documented hex-equivalent values.
 */
const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a2e" },
  header: { marginBottom: 24, borderBottom: "2px solid #6d4fe0", paddingBottom: 12 },
  title: { fontSize: 20, fontWeight: 700, color: "#6d4fe0" },
  subtitle: { fontSize: 10, color: "#666", marginTop: 4 },
  sectionTitle: { fontSize: 13, fontWeight: 700, marginTop: 18, marginBottom: 8 },
  paragraph: { fontSize: 11, lineHeight: 1.5, marginBottom: 8 },
  bullet: { fontSize: 10.5, lineHeight: 1.5, marginBottom: 4, paddingLeft: 12 },
  metricsGrid: { flexDirection: "row", flexWrap: "wrap", marginTop: 8, gap: 12 },
  metricBox: { border: "1px solid #ddd", borderRadius: 4, padding: 10, width: "31%" },
  metricLabel: { fontSize: 9, color: "#666" },
  metricValue: { fontSize: 16, fontWeight: 700, marginTop: 2 },
  footer: { position: "absolute", bottom: 24, left: 48, right: 48, fontSize: 8, color: "#999", textAlign: "center" }
});

export interface ReportPdfProps {
  orgName: string;
  metrics: ReportMetrics;
  output: ReportAgentOutput;
  usedFallback: boolean;
}

function ReportDocument({ orgName, metrics, output, usedFallback }: ReportPdfProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Weekly Executive Report</Text>
          <Text style={styles.subtitle}>
            {orgName} · {metrics.periodStart} to {metrics.periodEnd}
            {usedFallback ? " · Generated from live metrics (AI narrative unavailable this run)" : ""}
          </Text>
        </View>

        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={styles.paragraph}>{output.executiveSummary}</Text>
        {output.trendComparison && <Text style={styles.paragraph}>Trend: {output.trendComparison}</Text>}

        <View style={styles.metricsGrid}>
          <View style={styles.metricBox}>
            <Text style={styles.metricLabel}>Tasks Completed</Text>
            <Text style={styles.metricValue}>
              {metrics.tasksCompleted}/{metrics.tasksCreated}
            </Text>
          </View>
          <View style={styles.metricBox}>
            <Text style={styles.metricLabel}>Overdue Tasks</Text>
            <Text style={styles.metricValue}>{metrics.overdueTasks}</Text>
          </View>
          <View style={styles.metricBox}>
            <Text style={styles.metricLabel}>High-Severity Risks</Text>
            <Text style={styles.metricValue}>{metrics.activeRisksBySeverity.high}</Text>
          </View>
        </View>

        {output.highlights.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Highlights</Text>
            {output.highlights.map((item, i) => (
              <Text key={i} style={styles.bullet}>
                • {item}
              </Text>
            ))}
          </>
        )}

        {output.risks.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Risks</Text>
            {output.risks.map((item, i) => (
              <Text key={i} style={styles.bullet}>
                • {item}
              </Text>
            ))}
          </>
        )}

        {output.recommendations.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Recommendations</Text>
            {output.recommendations.map((item, i) => (
              <Text key={i} style={styles.bullet}>
                • {item}
              </Text>
            ))}
          </>
        )}

        <Text style={styles.footer} fixed>
          Generated by AI Operations Manager · {new Date().toISOString().slice(0, 10)}
        </Text>
      </Page>
    </Document>
  );
}

export async function generateReportPdfBuffer(props: ReportPdfProps): Promise<Buffer> {
  return renderToBuffer(<ReportDocument {...props} />);
}
